### ISSUE TITLE
An unhandled error after closing cluster preview mode

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#653] opened 2021-11-11 21:44 UTC
**Describe the bug**
After closing cluster previewing mode. I received an unhandled error.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1063" alt="Screen Shot 2021-11-12 at 00 41 46" src="https://user-images.githubusercontent.com/2957624/141373213-309b3505-1671-4819-822d-1119561bddd0.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Version Monokle 1.2.2

**Additional context**

**Comment by catalinhoha** [comment] 2021-11-13 15:50
Were you able to reproduce this?

**Comment by erdkse** [comment] 2021-11-13 16:12
unfortunately no

**Comment by olensmar** [comment] 2021-11-17 09:05
I can reproduce it..

**Comment by olensmar** [comment] 2021-11-17 09:47
Seems to be fixed in #683

**Closed by olensmar** 2021-11-17 09:47 UTC
Labels: bug
