### ISSUE TITLE
Add support for sealed-secrets

### ISSUE THREAD

**Issue by pentago** [kubeshop/monokle#1417] opened 2022-03-02 14:23 UTC
Adding support for [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) will resolve situation where references to sealed secret resources won't be displayed as unsatisfied link:
![screenshot](https://i.imgur.com/3Y8BE4K.png)

**Comment by devcatalin** [comment] 2022-03-02 14:46
Hi @pentago , thanks for your suggestion, we will discuss this within the team and come back to you with an update.

**Comment by pentago** [comment] 2022-03-02 14:49
Thanks @devcatalin! A lot of people in the industry are using sealed-secrets and I reckon this will be great addition that is hopefully easy to install (_e.g. if there's no secret with problematic name existing as a YAML/Kustomize manifest, look for sealed-secret resource of the same name_).

**Comment by olensmar** [comment] 2022-03-07 08:10
Hi @pentago - i've added initial support for this as requested (I hope) in #1439 - the only crux is that the SealedSecret CRD at https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/crds/sealedsecret-crd.yaml doesn't really provide a usable schema for validation/form functionality - is there a more elaborate schema available? or is this by design?

**Comment by olensmar** [comment] 2022-03-07 19:58
thanks @pentago - yes it helps - i'll see if I can create a schema so Monokle can provide proper validation and Form input for SealedSecrets also

**Comment by olensmar** [comment] 2022-03-09 12:10
@pentago this was merged into main yesterday and should be in the nightly-build - if you have time to try it out please let us know if it works as expected! thanks again for adding the issue!

**Closed as completed by olensmar** 2022-03-09 12:10 UTC
Labels: enhancement
