### ISSUE TITLE
Sync monokle with current context

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#1794] opened 2022-05-17 06:37 UTC
**Is your feature request related to a problem? Please describe.**

When opening Monokle project Kubernetes context is different that one selected in kubeconfig

<img width="1261" alt="Zrzut ekranu 2022-05-17 o 08 35 22" src="https://user-images.githubusercontent.com/30776/168745168-bac5dff9-6c93-4be6-ae99-a5e98eec544e.png">

**Comment by devcatalin** [comment] 2022-06-14 13:23
Duplicate of https://github.com/kubeshop/monokle/issues/1418

**Closed by devcatalin** 2022-06-14 13:23 UTC
