### ISSUE TITLE
Option to not group by namespace in compare

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2747] opened 2022-11-16 14:41 UTC
I'm trying to compare the output of two Kustomize overlays - but since they target different namespaces I can't see any other differences between the resources since Monokle shows them grouped by namespace (see below) - here I would like to ignore the namespace in the comparison - and just use the name to identify matching resources

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/1917063/202210257-9bb6fad5-5e35-4ea9-9e4e-7e2af28da6ab.png">

**Comment by devcatalin** [comment] 2022-11-16 14:42
Duplicate of https://github.com/kubeshop/monokle/issues/1995 ?
Razvan has started working on this today and already has something working, probably we will merge it soon!

**Comment by olensmar** [comment] 2022-11-16 15:02
yes - you're right - it's a different use-case (kustomize previews vs cluster compare) - but the underlying issue seems to be the same.. thank you @devcatalin for noticing!

**Closed** 2022-11-16 15:45 UTC
Labels: enhancement
