### ISSUE TITLE
Git loading stuck

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#3309] opened 2023-02-23 11:09 UTC
Sometimes when you open a project the git loading is getting stuck so you can't use the git features anymore.

**Comment by chargio** [comment] 2023-03-06 11:32
Do we have an example for this?

**Comment by chargio** [comment] 2023-03-06 11:32
Ask @WitoDelnat to see if we can reproduce it again

**Comment by WitoDelnat** [comment] 2023-03-28 07:26
Didn't realise there was already an existing issue. This is a duplicate of [unhandled git errors](https://github.com/kubeshop/monokle/issues/3540)

**Comment by olensmar** [comment] 2023-04-04 07:16
closing since it's a duplicate

**Closed by olensmar** 2023-04-04 07:16 UTC
Labels: bug, size/M, critical
