### ISSUE TITLE
Compiling/running on Linux crashes

### ISSUE THREAD

**Issue by srgvg** [kubeshop/monokle#473] opened 2021-10-05 08:54 UTC
**Describe the bug**
In absence of any Linux releases (#351) I'm trying to `npm install` and `npm run` on Linux

**To Reproduce**
On current Ddebian stable `11.0`

```
~/src/util/kubeshop-monokle ➞  git co v1.2.0
Note: switching to 'v1.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5ca1b6c chore(release): 1.2.0



~/src/util/kubeshop-monokle   ➞  npm install

> monokle@1.2.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.11.11
  • loaded configuration  file=package.json ("build" field)

> monokle@1.2.0 prepare
> husky install

husky - Git hooks installed

changed 1 package in 10s

~/src/util/kubeshop-monokle   ➞  cat /etc/debian_version
11.0

serge@minos ~/src/util/kubeshop-monokle   ➞  npm run electron:dev

> monokle@1.2.0 electron:dev
> concurrently "cross-env BROWSER=none npm run start" "wait-on http://localhost:3000 && tsc -p electron -w" "wait-on http://localhost:3000 && tsc -p electron && electron ."

[0]
[0] > monokle@1.2.0 start
[0] > craco start
[0]
[0] The following changes are being made to your tsconfig.json file:
[0]   - compilerOptions.paths must not be set (aliased imports are not supported)
[0]
[0] ℹ ｢wds｣: Project is running at http://172.31.32.32/
[0] ℹ ｢wds｣: webpack output is served from
[0] ℹ ｢wds｣: Content not from webpack is served from /home/serge/src/util/kubeshop-monokle/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[0] node:events:368
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: ENOSPC: System limit for number of file watchers reached, watch '/home/serge/src/util/kubeshop-monokle/public'
[0]     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
[0]     at Object.watch (node:fs:2247:34)
[0]     at createFsWatchInstance (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
[0]     at setFsWatchListener (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
[0]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
[0]     at FSWatcher.NodeFsHandler._handleDir (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:429:19)
[0]     at FSWatcher.<anonymous> (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:477:19)
[0]     at FSWatcher.<anonymous> (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:482:16)
[0]     at FSReqCallback.oncomplete (node:fs:199:5)
[0] Emitted 'error' event on FSWatcher instance at:
[0]     at FSWatcher._handleError (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
[0]     at createFsWatchInstance (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
[0]     at setFsWatchListener (/home/serge/src/util/kubeshop-monokle/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
[0]     [... lines matching original stack trace ...]
[0]     at FSReqCallback.oncomplete (node:fs:199:5) {
[0]   errno: -28,
[0]   syscall: 'watch',
[0]   code: 'ENOSPC',
[0]   path: '/home/serge/src/util/kubeshop-monokle/public',
[0]   filename: '/home/serge/src/util/kubeshop-monokle/public'
[0] }
[0] cross-env BROWSER=none npm run start exited with code 1
```
**Expected behavior**
Application just launches, without errors.

**Screenshots**
n/a
no browser or any graphical application is being started

**Desktop (please complete the following information):**
 - OS:Debian Stable v11
 - i3wm

**Comment by olensmar** [comment] 2021-10-05 09:01
thanks for this! what versions of node / npm are you using?

**Comment by srgvg** [comment] 2021-10-05 09:06
➞  node --version
`v16.10.0`

 ➞  npm --version
`7.24.0`

**Comment by srgvg** [comment] 2021-10-05 09:07
➞  which npm
`/home/serge/.nvm/versions/node/v16.10.0/bin/npm`

 ➞  which node
`/home/serge/.nvm/versions/node/v16.10.0/bin/node`

**Comment by olensmar** [comment] 2021-10-05 09:20
ok thanks - I think that should work - we're trying to reproduce on our end

**Comment by dobegor** [comment] 2021-10-05 09:25
@srgvg could you please post the output of `sudo sysctl -a | grep inotify`? (the command will post current system settings, filtering those that correspond to a maximum number of inotify watch objects)

**Comment by srgvg** [comment] 2021-10-05 09:27
```
 ➞  sudo sysctl -a | grep inotify

fs.inotify.max_queued_events = 1048576
fs.inotify.max_user_instances = 256
fs.inotify.max_user_watches = 100000
user.max_inotify_instances = 256
user.max_inotify_watches = 100000
```

**Comment by dobegor** [comment] 2021-10-05 09:32
Let's try to increase that value: (this is temporary, this configuration won't persist across reboots)
```
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl user.max_inotify_watches = 524288
sudo sysctl -p
```
And try to relaunch Monokle (preferably in same terminal session). React hot-reloads projects in development mode and watches for _all_ files, including node_modules (sic!).

**Comment by srgvg** [comment] 2021-10-05 09:40
second command gave this error
```
➞  sudo sysctl user.max_inotify_watches = 524288
user.max_inotify_watches = 524288
sysctl: malformed setting "="
sysctl: cannot stat /proc/sys/524288: No such file or directory
```
but even then, launching run electron:dev seems to work now: 

```
> monokle@1.2.0 start
> craco start

The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)

ℹ ｢wds｣: Project is running at http://172.31.32.32/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /home/serge/src/util/kubeshop-monokle/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
```
The url mentioned isn't right though, but I see a node process listening on `0.0.0.0:3000`.
Browsing localhost:3000 doesn't yiels any display. In devtools I do see some errors
```
Uncaught ReferenceError: require is not defined
    events external "events":1
    Webpack 13
external "events":1
    events external "events":1
    Webpack 13
```
In the console, I see this
```
11:37:00 AM - Starting compilation in watch mode...
[1]
[0] Files successfully emitted, waiting for typecheck results...
[1]
[1] 11:37:54 AM - Found 0 errors. Watching for file changes.
[2] 11:37:55.461 › App threw an error during load
[2] 11:37:55.470 › Error: ENOENT: no such file or directory, open '/home/serge/src/util/kubeshop-monokle/node_modules/electron/dist/resources/resources/schemas/k8sschemas.json'
[2]     at Object.openSync (fs.js:476:3)
[2]     at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
[2]     at Object.readFileSync (fs.js:377:35)
[2]     at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
[2]     at Object.loadResource (/home/serge/src/util/kubeshop-monokle/build/src/redux/services/index.js:23:25)
[2]     at Object.<anonymous> (/home/serge/src/util/kubeshop-monokle/build/src/redux/services/schema.js:11:41)
[2]     at Module._compile (internal/modules/cjs/loader.js:1078:30)
[2]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[2]     at Module.load (internal/modules/cjs/loader.js:935:32)
[2]     at Module._load (internal/modules/cjs/loader.js:776:14)
[2] A JavaScript error occurred in the main process
[2] Uncaught Exception:
[2] Error: ENOENT: no such file or directory, open '/home/serge/src/util/kubeshop-monokle/node_modules/electron/dist/resources/resources/schemas/k8sschemas.json'
[2]     at Object.openSync (fs.js:476:3)
[2]     at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
[2]     at Object.readFileSync (fs.js:377:35)
[2]     at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
[2]     at Object.loadResource (/home/serge/src/util/kubeshop-monokle/build/src/redux/services/index.js:23:25)
[2]     at Object.<anonymous> (/home/serge/src/util/kubeshop-monokle/build/src/redux/services/schema.js:11:41)
[2]     at Module._compile (internal/modules/cjs/loader.js:1078:30)
[2]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[2]     at Module.load (internal/modules/cjs/loader.js:935:32)
[2]     at Module._load (internal/modules/cjs/loader.js:776:14)
```

**Comment by olensmar** [comment] 2021-10-06 06:11
Hi @srgvg - we've merge a possible fix for this (#476) into main - let us know if you have the possibility to try it and if it works (or not...) - thanks again for all your feedback!

**Comment by srgvg** [comment] 2021-10-06 07:06
#476 seems to make it work yes; at first I thought not, but it seems after the initial startup, it's still copiling some stuff in the background, and the electron Window only appears after a couple of minutes, as I accidentely found out.. I had no idea I should have waited so long for that :-)

FWIW, the background process still yields some errors, but I don't know how relevant those are:

```
9:02:20 AM - Starting compilation in watch mode...
[1]
[1]
[1] 9:02:59 AM - Found 0 errors. Watching for file changes.
[2] 09:03:01.274 › Error: Your platform is not supported
[2]     at /home/serge/src/util/kubeshop-monokle/build/cli/terminal.js:14:20
[2]     at new Promise (<anonymous>)
[2]     at Object.exports.default (/home/serge/src/util/kubeshop-monokle/build/cli/terminal.js:9:12)
[2]     at Object.<anonymous> (/home/serge/src/util/kubeshop-monokle/build/electron/main.js:277:19)
[2]     at Module._compile (internal/modules/cjs/loader.js:1078:30)
[2]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[2]     at Module.load (internal/modules/cjs/loader.js:935:32)
[2]     at Module._load (internal/modules/cjs/loader.js:776:14)
[2]     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
[2]     at loadApplicationPackage (/home/serge/src/util/kubeshop-monokle/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)
[2] 09:03:01.546 › info monokle 1.2.0 en-US null
[2] 09:03:03.220 › (node:2528772) ExtensionLoadWarning: Warnings loading extension at /home/serge/.config/monokle/extensions/fmkadmapgofadopljbjfkapdkoienihi:
[2]   Unrecognized manifest key 'browser_action'.
[2]   Unrecognized manifest key 'minimum_chrome_version'.
[2]   Unrecognized manifest key 'update_url'.
[2]   Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
[2]
[2] (Use `electron --trace-warnings ...` to show where the warning was created)
[2] 09:03:03.224 › Added Extension:  React Developer Tools
[2] 09:03:03.491 › (node:2528772) ExtensionLoadWarning: Warnings loading extension at /home/serge/.config/monokle/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
[2]   Unrecognized manifest key 'commands'.
[2]   Unrecognized manifest key 'homepage_url'.
[2]   Unrecognized manifest key 'page_action'.
[2]   Unrecognized manifest key 'short_name'.
[2]   Unrecognized manifest key 'update_url'.
[2]   Permission 'notifications' is unknown or URL pattern is malformed.
[2]   Permission 'contextMenus' is unknown or URL pattern is malformed.
[2]   Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
[2]
[2] 09:03:03.492 › Added Extension:  Redux DevTools
[2] 09:03:07.406 › Checking for update
[2] 09:03:07.481 › Error: Error: ENOENT: no such file or directory, open '/home/serge/src/util/kubeshop-monokle/dev-app-update.yml'
```

Thanks for this quick update. Hope you can also add this as a Linux release now!

**Comment by olensmar** [comment] 2021-10-06 08:51
Thanks for testing and getting back to us! Hopefully you can use Monokle now as intended - let us know if you have any issues/requests/etc!

Linux release coming up - #351 !

/Ole

**Closed by olensmar** 2021-10-06 08:52 UTC
