### ISSUE TITLE
quick-search in list of projects

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3983] opened 2023-05-24 08:00 UTC
I have a lot of projects (50+) and would like to have a quick search field where I can enter a string that would filter out all projects that don't contain the provided string in the name..

**Comment by ayushgml** [comment] 2023-05-24 17:06
Hey @olensmar! I want to work on this issue and can i be assigned this? 
This is what I perceive and correct me if I am wrong:
 - You want a similar search like ```SearchContainer``` in ```StartPageHeader.tsx```. It is just that SearchContainer filters out on the basis of project that start with a string. You want a search bar that filters out projects if the input string is anywhere present in the project name and not only at the starting?
 
 My doubt:
  - You want a separate search bar for that or that functionality should be included in the same search bar but instead of startsWith function, a function that filters out projects that don't contain a string?

**Comment by ayushgml** [comment] 2023-05-25 06:16
I think the placement of the search box is optimal. What should be the placeholder in the text box @olensmar ? Because the top left search bar in the header also mentions "Find repositories and projects".

**Comment by olensmar** [comment] 2023-05-25 07:03
let's await @julioramosest input - he's our UX master - I agree it might be a bit confusing with both a search box on the top left and on top of the list of projects - perhaps having both is overkill!? 

On another note - we should fix the top left search box (if we keep it):
- do a substring search
- change placeholder to just "Find project" - since we're not searching repositories afaik!?

**Comment by julioramosest** [comment] 2023-05-25 11:00
@ayushgml @olensmar Hey there! So
- **Global search on top left**: goal for this is to find not only projects, but also other relevant content within projects (file names for example? clusters?), settings, even documentation. We needed to trim scope for this in order to have something out. I think this still makes sense even in it's simplified form. We need to take it to that more useful state, but I would not get rid of it in the meantime
- Quick project finder: this makes sense and it's perfectly fine to have it in corresponding section. Expected behaviour: it just filters the main projects list below it, showing only matching ones. User can quicly select any of them. Deleting text string shows back all projects. Matching text can be highlighted in the product cards with text bg color geekblue-9 (Ant dark palette, hexadecimal A8C1F8). See design below:

https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?type=design&node-id=1239%3A7738&t=wKvQa0vXbGDkfvKo-1

<img width="1440" alt="desktop - All projects" src="https://github.com/kubeshop/monokle/assets/97731654/997ccbd2-9ac5-4b2d-9dd7-e3698f29c4a5">

**Comment by olensmar** [comment] 2023-05-25 11:14
thanks @julioramosest - you should be all set @ayushgml !

**Comment by ayushgml** [comment] 2023-05-25 11:16
@julioramosest Great take on the UX part! I will start working on this @olensmar and while working if i encounter any doubts, I will post them here.

**Comment by ayushgml** [comment] 2023-05-26 04:50
Hey @julioramosest I am done with the project filter search bar part. Before moving on to Global search, I just wanted to ask for the lightning SVG in project search bar because I am having trouble extracting it. Could you please tel me how to extract it?

**Comment by ayushgml** [comment] 2023-05-26 05:09
The highlighted test looks like this:

<img width="1536" alt="Screenshot 2023-05-26 at 10 37 03 AM" src="https://github.com/kubeshop/monokle/assets/72748253/ec22a72c-61a7-4806-a73f-b60b36eba03b">

The background of text is hexadecimal A8C1F8 as you guided. But the text itself is white which makes it kind of invisible. According to you is it okay to keep it like this @julioramosest or should i change the text color to something else?

**Comment by ayushgml** [comment] 2023-05-26 05:26
@olensmar suppose user searches some string in the project search bar which is not present as a substring in any of the projects. Then what should the page display? Something like "No projects found" or just a blank page? @julioramosest what do you suggest?

**Comment by olensmar** [comment] 2023-05-26 06:20
hm.. I think "no matching projects found" is good enough in this case

**Comment by ayushgml** [comment] 2023-05-26 06:32
Also @olensmar to make the global search, I would need a list of settings and documentation as @julioramosest said that it would be a global search. Can you guide me on how to get started on this to get these lists?
Currently, ```SettingsPane``` is in organism folder and each setting has their own component. There is no list. Should i start to make one and then manually route each item in the list to respective setting?

**Comment by olensmar** [comment] 2023-05-26 06:33
@ayushgml I created a separate issue for the global search - #3996 - let's discuss there..

**Comment by ayushgml** [comment] 2023-05-26 09:06
The current UI looks like this:
<img width="1536" alt="Screenshot 2023-05-26 at 2 29 32 PM" src="https://github.com/kubeshop/monokle/assets/72748253/8ca0845e-1bc4-4c87-b1b5-472cf89d66ce">
<img width="1536" alt="Screenshot 2023-05-26 at 2 30 16 PM" src="https://github.com/kubeshop/monokle/assets/72748253/9ec0f9fa-3ac9-4661-85ba-64097f2ac691">
<img width="1535" alt="Screenshot 2023-05-26 at 2 30 47 PM" src="https://github.com/kubeshop/monokle/assets/72748253/80412fc2-80d9-48e1-8c31-aaf4b4a71ff6">

Are there any changes that i need to make @olensmar @julioramosest ?

**Comment by olensmar** [comment] 2023-05-26 09:43
@ayushgml looks great - ship it!

**Comment by ayushgml** [comment] 2023-05-26 09:59
Done! Created a pull request @olensmar 
 - #4000

**Comment by julioramosest** [comment] 2023-05-26 10:10
Looks like I'm late to the party! see you managed your way to the lightning icon ;) Nice work @ayushgml! Thanks @olensmar for quick-assisting Ayush today

**Comment by ayushgml** [comment] 2023-05-26 10:13
Thanks @julioramosest and @olensmar for helping me with this! I'm really enjoying these contributions and learning from you guys!

**Comment by julioramosest** [comment] 2023-05-26 10:23
![lightning-svgrepo-com 1](https://github.com/kubeshop/monokle/assets/97731654/da3f1b8c-e3bb-4117-999b-c910fc06acee)

(at risk of being annoying) this would be original SVG icon, a bit less prominent. Wouldn't be too much if we have a new PR including this? And now we are at it, we can have the label "Quick project search" with only the first letter in caps? we are not using all-words-in-caps in the tool. @ayushgml let me know if the SVG can be extracted easily from this comment

**Comment by ayushgml** [comment] 2023-05-26 10:38
Yes @julioramosest I will create a new pull request with these changes. I extracted the SVG and this is the look:

<img width="1535" alt="Screenshot 2023-05-26 at 2 30 47 PM" src="https://github.com/kubeshop/monokle/assets/72748253/aed494be-9ce0-4c9e-bb0b-e2ecf1f9a42f">

**Comment by julioramosest** [comment] 2023-05-26 10:48
really appreciate @ayushgml !

**Comment by ayushgml** [comment] 2023-05-26 10:50
Thank you @julioramosest !

**Closed** 2023-05-29 07:41 UTC
Labels: enhancement, needs-ux, nice-to-have
