### ISSUE TITLE
Crash when switching to form editor 

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/monokle#4072] opened 2023-06-14 08:44 UTC
**Describe the bug**
the app crashes while switching to the form editor 

**To Reproduce**
1. select a resource
2.  tab on the form
3. See the error

**Screenshots**
![Screenshot 2023-06-14 at 11 39 17 AM](https://github.com/kubeshop/monokle/assets/20525304/924d7ace-01d7-4b80-82ee-2d60358c9d74)
![Screenshot 2023-06-14 at 11 40 40 AM](https://github.com/kubeshop/monokle/assets/20525304/057ce6d5-7266-44f3-8367-0ef2b7a1ec36)

**Desktop (please complete the following information):**
 - OS: mac m1
 - Version: main branch

**Comment by olensmar** [comment] 2023-06-14 09:49
this is a duplicate of https://github.com/kubeshop/monokle/issues/3879 - it's related to some schema construct that rjsf doesn't handle well..

**Closed** 2023-06-16 09:28 UTC
Labels: bug
