### ISSUE TITLE
Monokle app turns completely black when clicking on the "Namespace" drop-down selector

### ISSUE THREAD

**Issue by ryanjafari** [kubeshop/monokle#826] opened 2021-12-02 14:17 UTC
**Describe the bug**
Monokle app turns completely black when clicking on the "Namespace" drop-down selector in the "Create New Resource" modal.

**To Reproduce**
1. Open Monokle
2. Click on '+' sign in middle pane to create new resource
3. Click on "Namespace" drop-down selector input
4. Black screen & app is no longer responsive

**Expected behavior**
I can see some namespaces to choose from.

**Screenshots**
<img width="1312" alt="Screen Shot 2021-12-02 at 9 13 31 AM" src="https://user-images.githubusercontent.com/29539/144438679-328ed265-7482-4ae8-bbdd-4e98fba36d9f.png">

**Desktop (please complete the following information):**
 - macOS Monterey 12.1 Beta (21C5045a)
 - Monokle v1.3.3

**Additional context**
macOS Console.app output for process "Monokle" around the time of the problem:

[macos-console-output-for-monokle.log](https://github.com/kubeshop/monokle/files/7642581/macos-console-output-for-monokle.log)

**Comment by olensmar** [comment] 2021-12-02 14:24
Hi @ryanjafari - thanks for reporting! Did you have a folder opened when this happened? Could you please enable the developer console (option-cmd-I or from the View menu) to see if you get any additional error output when this happens and let us know? thanks!

**Comment by ryanjafari** [comment] 2021-12-02 16:34
The file explorer in the left-most pane does have a folder open with a lot of stuff inside (subdirectories and yamls).

![Screen Shot 2021-12-02 at 11 33 23 AM](https://user-images.githubusercontent.com/29539/144463500-3082aaf4-4625-4000-9004-cea4d8213a65.png)

And sorry about that, I forgot it was web-based.

From the developer console:

```
react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7B%20.Release.Namespace%20%7D%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ko (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Vs (react-dom.production.min.js:176)
    at Ga (react-dom.production.min.js:271)
    at Nl (react-dom.production.min.js:250)
    at Tl (react-dom.production.min.js:250)
    at xl (react-dom.production.min.js:250)
    at wl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
da @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
go @ react-dom.production.min.js:131
ya @ react-dom.production.min.js:220
zl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Kr @ react-dom.production.min.js:122
Al @ react-dom.production.min.js:252
wl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Kr @ react-dom.production.min.js:122
Yr @ react-dom.production.min.js:123
Gr @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
Jt @ react-dom.production.min.js:73
react-dom.production.min.js:140 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7B%20.Release.Namespace%20%7D%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ko (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Vs (react-dom.production.min.js:176)
    at Ga (react-dom.production.min.js:271)
    at Nl (react-dom.production.min.js:250)
    at Tl (react-dom.production.min.js:250)
    at xl (react-dom.production.min.js:250)
    at wl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

**Comment by ryanjafari** [comment] 2021-12-02 16:37
Thanks for the promising project. I found it when I was searching for better ways to work with / visualize all this k8s YAML.

**Comment by olensmar** [comment] 2021-12-02 17:09
thanks @ryanjafari - this seems to be fixed in the upcoming 1.4.0 release (we can reproduce in 1.3.3) - you could try the latest nightly build to validate - https://github.com/kubeshop/monokle/releases/tag/untagged-7d4b06e96e7bb3167acf 

ultimately this is related to our somewhat lacking Helm template support - we have a bunch of things planned for Helm-related functionality - if you have any special requests/suggestions we would love to hear them!

**Comment by ryanjafari** [comment] 2021-12-02 17:33
Beautiful @olensmar - it is fixed in that build! I'll certainly be in touch with feedback now.

**Comment by olensmar** [comment] 2021-12-02 17:48
awesome - looking forward!

**Closed by olensmar** 2021-12-02 17:48 UTC
Labels: bug
