### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2259] opened 2022-08-22 11:10 UTC
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Cannot access 'previewConfiguration' before initialization
 ReferenceError: Cannot access 'previewConfiguration' before initialization
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:29552:845
    at a (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:656070:13)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:656093:14
    at q (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:655974:11)
    at exports.useSyncExternalStoreWithSelector (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:656098:11)
    at useSelector (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:615745:27)
    at PreviwConfigurationDetails (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:29552:836)
    at Ch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:607682:7)
    at ck (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:610723:11)
    at bk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:610197:11)
```

**Comment by devcatalin** [comment] 2022-08-24 09:07
Duplicate of https://github.com/kubeshop/monokle/issues/2224

**Closed by devcatalin** 2022-08-24 09:07 UTC
Labels: bug
